### ISSUE TITLE
Duplicate effort: please collaborate

### ISSUE THREAD

**Issue by anantshri** [hashishrajan/cloud-security-vulnerabilities#1]
summitroute @0xdabbad00 has been maintaining a list already https://github.com/SummitRoute/csp_security_mistakes 

Would suggest contributing to that list.

**Comment by hashishrajan** [comment]
Thank you for sharing this @anantshri ! I appreciate the thought that particular repo will not be maintained anymore is my understanding. Is this not right?

**Comment by 0xdabbad00** [comment]
cloudvulndb.org should take over all the findings I had on my repo.

**Comment by hashishrajan** [comment]
Thanks @0xdabbad00 for clarifying that and the link. Definitely looks like good work I should be referring to here in my list.  I will replace the csp_security_mistakes repo with this website in my list here!

Thank you @anantshri - hope you are ok for me to close this issue. Feel free to re-open another issue, if you feel this needs further discussion.
